"""Regenerate README.md's ledger-statistics table from LEDGER.md.

    uv run python scripts/ledger_stats.py

The table is COMPUTED, never typed: this script parses LEDGER.md (and
PROMOTED_QUEUE.md) and rewrites README.md between the LEDGER_STATS
markers, so the README cannot drift into claiming numbers the ledger does
not back. Run it after any run; commit the diff.
"""

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- LEDGER_STATS:BEGIN (generated by scripts/ledger_stats.py — do not edit by hand) -->"
END = "<!-- LEDGER_STATS:END -->"

_LINE_RE = re.compile(r"^#(\d+)\s*\|\s*(\S+)\s*\|\s*(\S+)\s*\|")


def parse_ledger(text: str) -> dict:
    stats = {"tested": 0, "killed_merits": 0, "killed_infra": 0,
             "iterated": 0, "promoted": 0}
    for line in text.splitlines():
        match = _LINE_RE.match(line.strip())
        if not match:
            continue
        stats["tested"] += 1
        label = match.group(3)
        if label.startswith("ITERATED->"):
            stats["iterated"] += 1
            label = label[len("ITERATED->"):]
        if label == "KILLED(merits)":
            stats["killed_merits"] += 1
        elif label == "KILLED(infrastructure)":
            stats["killed_infra"] += 1
        elif label == "PROMOTED":
            stats["promoted"] += 1
    return stats


def count_holdout_runs(promoted_queue_text: str) -> int:
    """Holdout execution is human-only and single-shot; a queue entry only
    counts as a RUN once a holdout memo exists. No memos exist yet, so
    this counts hypothesis dirs containing a holdout_memo.md."""
    return len(list((REPO_ROOT / "hypotheses").glob("H*/holdout_memo.md")))


def render_table(stats: dict, holdout_runs: int) -> str:
    infra_rate = (stats["killed_infra"] / stats["tested"] * 100) if stats["tested"] else 0.0
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return "\n".join([
        "| statistic | count |",
        "|---|---|",
        f"| hypotheses tested | {stats['tested']} |",
        f"| killed on merits | {stats['killed_merits']} |",
        f"| killed on infrastructure | {stats['killed_infra']} |",
        f"| exhausted their iteration budget before dying | {stats['iterated']} |",
        f"| promoted | {stats['promoted']} |",
        f"| single-shot holdout runs (human-only) | {holdout_runs} |",
        f"| infrastructure-kill rate | {infra_rate:.1f}% |",
        "",
        f"*Computed from [LEDGER.md](LEDGER.md) by "
        f"[scripts/ledger_stats.py](scripts/ledger_stats.py) on {generated} "
        f"— the table regenerates from the ledger and cannot drift from it.*",
    ])


def main() -> int:
    ledger = (REPO_ROOT / "LEDGER.md").read_text(encoding="utf-8")
    stats = parse_ledger(ledger)
    table = render_table(stats, count_holdout_runs(""))

    readme_path = REPO_ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    if BEGIN not in readme or END not in readme:
        print(f"ERROR: README.md lacks the {BEGIN.split(' ')[0]}... markers",
              file=sys.stderr)
        return 1
    head, rest = readme.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    readme_path.write_text(head + BEGIN + "\n" + table + "\n" + END + tail,
                           encoding="utf-8")
    print(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
